### ISSUE TITLE
Replace exceeding 8+ minutes on a 10.5MB log file

### ISSUE THREAD

**Issue by darrengoulden-pex** [facelessuser/RegReplace#74] opened 2018-01-21 18:46 UTC
## Description

I'm using RegReplace to replace `^M` with `\n` in log files, I'm having an issue which seems to be specific to my Mac - even after a full rebuild. My colleagues are using the same rules as below and the same Sublime version (`Version 3.0, Build 3143`) but the issue is not present on their machines. The time taken to replace ^M with a newline far exceeds the in-built Sublime regex replace, please see video I sent.

reg_replace_rules.sublime-settings
```
{
	"format": "3.0",
	"replacements":
	{
		"replace_M":
		{
			"case": false,
			"find": "\\^M",
			"greedy": true,
			"replace": "\n"
		}
	}
}
```

Default.sublime-commands
```
[
 {
   "caption": "Reg Replace: Replace M",
   "command": "reg_replace",
   "args": {
     "replacements": [
       "replace_M"
     ]
   }
 },
]
```

## Support Info

Please see video, I am using the script below to generate the log file to test with (original found [here](http://www.thelinuxdaily.com/2010/12/creating-a-fluff-file-filled-with-specified-or-random-text/))

```bash
#!/bin/sh
 
# Variables; 2000000 = 2MB
max_size=10500000
filename=result.txt
tmpfilename=tmp.txt
string="2017-08-24T13:41:21.584+00:00 conf 2017-08-24 13:41:21,584 Level=\"INFO\" Name=\"support.sip\" Message=\"Received SIP request\" Src-address=\"10.0.0.1\" Src-port=\"37378\" Dst-address=\"10.1.1.1\" Dst-port=\"5061\" Transport=\"TLS\" Received-time=\"2017-08-24T13:41:21,578155\" Detail=\"^MNEGOTIATE sip:127.0.0.1:5061 SIP/2.0^MVia: SIP/2.0/TLS 10.0.0.1:37378;branch=z9hG4bK6404210D.0EE431E4497209B1;branched=FALSE^MMax-Forwards: 0^MFrom: sip:sipfed.domain.com;tag=BDEN82JCFEC37D1327571BC0ED5FF29A^MTo: sip:sip.domain.com^MCall-ID: F13DE9AB8828F2B26A3E^MCSeq: 1 NEGOTIATE^Mms-telemetry-id: 811FE024-3DA1-5595-8CC7-D453F008B930^MRequire: ms-feature-info^MSupported: NewNegotiate,OCSNative,ECC,IPv6,TlsRecordSplit,PstnTrafficType^MServer: RTC/7.0^MContent-Length: 0^M^M\""
 
# File checks so we don't overwrite somebody's important files
if [ -e $tmpfilename ]; then
        echo "File: $tmpfilename exists!"
        echo "This script is going to use this as a temporary file, so either"
        echo "modify the script variable $tmpfilename or remove the file."
        exit 1
fi
 
if [ -e $filename ]; then
        echo "File: $filename exists!"
        echo "Remove it and restart this script"
        exit 1
else
        echo $string > $filename
fi
 
# Initialize the variable
size=$(stat -f %z $filename)
 
# Start the loop, increasing the size of the file 2x until reaching max_size
while [ $size -lt $max_size ]; do
        cat $filename > $tmpfilename
        cat $tmpfilename >> $filename
        size=$(stat -f %z $filename)
done
 
# Chop off any excess
head -c $max_size $filename > $tmpfilename
mv $tmpfilename $filename
``` 

## Steps to Reproduce Issue

1. Open log file
2. Run RegReplace with user command

**Comment by facelessuser** [comment] 2018-01-21 22:03
I just tried it out, and it was done in seconds.  It wasn't instant, but about 2-3 seconds maybe?

I imagine there is more going on than just RegReplace.  I'm on ST3 3156.

So a little info on what RegReplace does.  It actually is not using the built-in regular expression engine that Sublime uses.  The API for that is a little awkward, and doesn't allow all the things that I am doing in RegReplace.  So it uses either Python's built-in Re (default) or the 3rd party Regex library (optional in settings).  It extracts the text from the view, applies the pattern getting back match objects, expands the replaces, and then inserts them back in the buffer one by one.

Now, because it inserts the regions one by one instead of the entire buffer, maybe that is triggering multiple events that some other plugin is triggering off of.  I'm not sure because I'm not seeing the issues.

If I didn't rely on Sublime scopes for some features, I'd probably work on the whole file in memory, then insert with one edit, but currently that is not the case.

I am assuming you are running with stock RegReplace settings?  Can you confirm?

I would also double check what other plugins you have installed as well.  It is possible some of them are kicking in on a buffer change and performing some expensive action. And since we have a bazillion inserts with this file, maybe that is what's doing it.

**Comment by facelessuser** [comment] 2018-01-22 00:13
Also, let me know if you are using a syntax highlighter on your log file, and if so, which?

**Comment by darrengoulden-pex** [comment] 2018-01-22 09:07
Here are my Sublime settings

```
{
	"auto_complete_delay": 5,
	"auto_complete_selector": "source, text",
	"create_window_at_startup": false,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".DS_Store",
		"__pycache__",
		"*.pyc",
		"*.pyo",
		"*.exe",
		"*.dll",
		"*.obj",
		"*.o",
		"*.a",
		"*.lib",
		"*.so",
		"*.dylib",
		"*.ncb",
		"*.sdf",
		"*.suo",
		"*.pdb",
		"*.idb",
		"*.psd"
	],
	"font_face": "Source Code Pro",
	"font_size": 13,
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
	"open_files_in_new_window": false,
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
```

No highlighting other than the built in Sublime stuff, I only have RegReplace and SublimeLog installed via package control, I have not modified the RegReplace settings so they are stock - is there a way to debug the process?

**Comment by facelessuser** [comment] 2018-01-22 14:58
I honestly don't see anything...I've installed SublimeLog, and that doesn't seem to interfere.  I've enabled `word_wrap` thinking maybe it was reflowing the text on every insert, but I don't see a problem with that.  You have autocomplete enabled in text, but I didn't see a problem with that setting.

Are you highlighting log text with something?  Or is it just plain text (no highlighting)?

**Comment by darrengoulden-pex** [comment] 2018-01-22 15:35
Just plain text, no highlighting for those log files, I'll keep digging..

**Comment by darrengoulden-pex** [comment] 2018-01-22 15:52
I've just wiped by Sublime settings file and it cleared the issue! every file I've tried opens within 10 seconds, something in the setting file (above) is causing the issue, I'll try and narrow it down if I get time tonight

**Comment by facelessuser** [comment] 2018-01-22 16:25
Cool.  Maybe it isn't anything in the settings, and something just corrupted with that install.  But if you find out anything, let me know.

**Comment by facelessuser** [comment] 2018-01-22 16:54
Essentially it seems to be as I mentioned expect it was a built-in plugin that was being triggered.  I guess this is much more pronounced on large files.

**Comment by facelessuser** [comment] 2018-01-22 17:01
Turns out, I do modify `translate_tabs_to_spaces`: https://github.com/facelessuser/RegReplace/blob/master/rr_replacer.py#L105.  So maybe the problem is that I'm doing this on **every** replace.  I should probably change this to be done once for the entire operation, and restored at the end.  Probably the flip flopping of this setting is causing some slow down.

**Comment by darrengoulden-pex** [comment] 2018-01-23 10:33
I'd be happy to test it again once its changed!

**Comment by facelessuser** [comment] 2018-01-23 14:26
Cool.  Not exactly sure when I'll get to this, but hopefully soonish.

**Comment by facelessuser** [comment] 2018-01-29 03:25
I was able to reproduce the issue and have applied a fix on this branch: https://github.com/facelessuser/RegReplace/tree/tab-space-fix.

**Comment by facelessuser** [comment] 2018-02-04 20:14
I'm assuming that branch fixed your issue so I merged it.

**Closed by facelessuser** 2018-02-04 20:14 UTC

**Comment by darrengoulden-pex** [comment] 2018-02-12 18:23
Hi, apologies, I've been out of the country, is this now included in the release?  I will test if so.

**Comment by facelessuser** [comment] 2018-02-12 18:25
Yup. Fix is in latest release.

**Comment by darrengoulden-pex** [comment] 2018-02-12 18:28
Works great, thanks for your help!
