### ISSUE TITLE
REGEX ERROR: unmatched group

### ISSUE THREAD

**Issue by luckman212** [facelessuser/RegReplace#107] opened 2023-08-29 18:33 UTC
## Description

I'm a beginner with this plugin, but I can't figure this out. I really tried!

I'm wanting to convert some older shell scripts from POSIX style `if` statements `[ -n "$foo" ]` to double-bracketed format for modern Bash, e.g. `[[ -n $foo ]]`

I'm using a set of regexp's to do this, and it's (mostly) working, but I'm stuck here on this error:

<img width="372" alt="d0397396ce236d1897c6bccbec8b4d3e2cbc3643_gh" src="https://github.com/facelessuser/RegReplace/assets/1992842/4b292104-9de3-4c7f-a866-f0e700a0da39">

It seems to be the `modernize_brackets_0` replacement, which has an optional capture group `\1` defined. When this doesn't match, the error is thrown. But, can't figure out how to simply ignore that and continue.

Here are the patterns:
```json
{
  "format": "3.0",
  "replacements": {
    "modernize_brackets_0": {
      "find": "(?<!\\[)\\[ (-. )?\"([^\"]+)\" \\](?![\\]])",
      "replace": "[[ \\1 \\2 ]]",
      "greedy": true
    },
    "modernize_brackets_1": {
      "find": "(?<!\\[)\\[ \"([^\"]+)\" ([^]]+) \\](?![\\]])",
      "replace": "[[ \\1 \\2 ]]",
      "greedy": true
    },
    "modernize_brackets_2": {
      "find": "(?<!\\[)\\[ ([^]]+) \\](?![\\]])",
      "replace": "[[ \\1 ]]",
      "greedy": true
    },
```

And here's my command:
```json
  {
    "caption": "RegReplace: Modernize Brackets",
    "command": "reg_replace",
    "args": {
      "replacements": [
        "modernize_brackets_0",
        "modernize_brackets_1",
        "modernize_brackets_2"
      ]
    }
  },
```

Here's my test input:
```
if [ "$foo" ]; then bar
[ "$foo" ] && bar
if [ -n "$foo" ] || [ -z $bar ]; then
if [ "$foo" == "bar" ]; then
[ $? -eq 0 ]
```

The _desired_ output after executing the macro:
```
if [[ $foo ]]; then bar
[[ $foo ]] && bar
if [[ -n $foo ]] || [[ -z $bar ]]; then
if [[ $foo == "bar" ]]; then
[[ $? -eq 0 ]]
```

Any help greatly appreciated! Do I need to write a [custom replace plugin](http://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins) to do this?

## Support Info

- ST ver.: 4155
- Platform: osx
- Arch: arm64
- Plugin ver.: 3.8.1
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.0
- regex ver.: Version could not be acquired!
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment] 2023-08-30 00:13
Can you let me know what options you have enabled? For instance, are your using `regex` or `re`? Are you using extended backrefs?

**Comment by facelessuser** [comment] 2023-08-30 00:15
Also, look in your console after running your command and capture the output error. I suspect there is one.

**Comment by facelessuser** [comment] 2023-08-30 03:18
I suspect `backrefs` which is about 6 releases behind the latest, has a bug that is causing this issue. If you were experiencing this, it is likely because you have `extended_backrefs` enabled.

If this is the case, I need to update `backrefs` in Sublime Text to the latest. As a workaround, disabling `extended_back_references` until `backrefs` is updated would fix your issue.

**Comment by luckman212** [comment] 2023-08-30 03:38
Thanks for peeking in on this! I'm not at my desk right now, but I'll check for those console logs a bit later.

I'm not using extended backrefs.

**Comment by facelessuser** [comment] 2023-08-30 04:23
I was able to reproduce your issue, but it was failing because `backrefs` was throwing some errors due to being out of date and not having the latest bug fixes. I patched it locally and then I got your expected output. The other difference was that I was using the `regex` library instead of `re`. So then I tested all configurations.

Turns out pure`re` (without `backrefs`) behaves differently than `regex`. Enabling `backrefs` gave us parity with `regex`. So `re` (at least on Python 3.3) has a quirk where if an optional group is not present, if your replace template tries to reference it, it can fail, so rewriting your pattern like so fixes it:

```js
        "modernize_brackets_0": {
	      "find": "(?<!\\[)\\[ ((?:-. )?)\"([^\"]+)\" \\](?![\\]])",
	      "replace": "[[ \\1 \\2 ]]",
	      "greedy": true
	},
```

Turns out the bug I found, wasn't even causing you issues.

**Comment by facelessuser** [comment] 2023-08-30 04:38
It also seems this `re` quirk is specific to older Python versions as I can't reproduce it with another tool I maintain using Python 3.11.

<img width="775" alt="Screenshot 2023-08-29 at 10 36 07 PM" src="https://github.com/facelessuser/RegReplace/assets/1055125/7e972a6d-99d7-498a-826b-22795e2bcdae">

**Comment by facelessuser** [comment] 2023-08-30 13:03
I've pushed a new version of `backrefs`, backported to Python 3.3. Assuming no issues with the backport, that should resolve issues there. It will probably take Package Control some time to make that available and push it out to machines. Since your issue was not with `backrefs`, this should not affect you.

As your issue is related to Python 3.3's handling of optional groups, your issue can be worked around with a simple change in your pattern.

Once Package Control supports Python 3.8 properly, we migrate to using it, and this issue will go away:

Python 3.3

```py
Python 3.3>>> text = """\nif [ "$foo" ]; then bar\n[ "$foo" ] && bar\nif [ -n "$foo" ] || [ -z $bar ]; then\nif [ "$foo" == "bar" ]; then\n[ $? -eq 0 ]\n"""
Python 3.3>>> re.sub(r'(?<!\[)\[ (-. )?"([^"]+)" \](?![\]])', r'[[ \1 \2 ]]', text, flags=re.M)
Traceback (most recent call last):
  File "__main__", line 1, in <module>
  File "./python3.3/re.py", line 170, in sub
  File "./python3.3/re.py", line 314, in filter
  File "./python3.3/sre_parse.py", line 868, in expand_template
sre_constants.error: unmatched group
```

Python 3.8

```py
>>> import re
>>> text = """\nif [ "$foo" ]; then bar\n[ "$foo" ] && bar\nif [ -n "$foo" ] || [ -z $bar ]; then\nif [ "$foo" == "bar" ]; then\n[ $? -eq 0 ]\n"""
>>> re.sub(r'(?<!\[)\[ (-. )?"([^"]+)" \](?![\]])', r'[[ \1 \2 ]]', text, flags=re.M)
'\nif [[  $foo ]]; then bar\n[[  $foo ]] && bar\nif [[ -n  $foo ]] || [ -z $bar ]; then\nif [ "$foo" == "bar" ]; then\n[ $? -eq 0 ]\n'
```

Modified pattern in Python 3.3

```py
Python 3.3>>> import re
Python 3.3>>> text = """\nif [ "$foo" ]; then bar\n[ "$foo" ] && bar\nif [ -n "$foo" ] || [ -z $bar ]; then\nif [ "$foo" == "bar" ]; then\n[ $? -eq 0 ]\n"""
Python 3.3>>> re.sub(r'(?<!\[)\[ ((?:-. )?)"([^"]+)" \](?![\]])', r'[[ \1 \2 ]]', text, flags=re.M)
'\nif [[  $foo ]]; then bar\n[[  $foo ]] && bar\nif [[ -n  $foo ]] || [ -z $bar ]; then\nif [ "$foo" == "bar" ]; then\n[ $? -eq 0 ]\n'
```

I will consider this issue resolved but will wait for confirmation before closing.

**Comment by luckman212** [comment] 2023-08-30 23:10
@facelessuser This is so helpful. Thank you kindly for the digging! 🚀 

Indeed, the modified pattern you posted fixed the problem! The regex melts my brain to look at. But here is what I've got now, in case it helps anyone:

## Default.sublime-commands
```json
[
  {
    "caption": "RegReplace: Modernize Brackets",
    "command": "reg_replace",
    "args": {
      "replacements": [
        "modernize_brackets_0",
        "modernize_brackets_1",
        "modernize_brackets_2"
      ]
    }
  },
```

## reg_replace_rules.sublime-settings

```json
{
  "format": "3.0",
  "replacements": {
    "modernize_brackets_0": {
      "find": "(?<!\\[)\\[ ((?:-. )?)\"([^\"]+)\" \\](?![\\]])",
      "replace": "[[ \\2 ]]",
      "greedy": true
    },
    "modernize_brackets_1": {
      "find": "(?<!\\[)\\[ \"([^\"]+)\" ([^]]+) \\](?![\\]])",
      "replace": "[[ \\1 \\2 ]]",
      "greedy": true
    },
    "modernize_brackets_2": {
      "find": "(?<!\\[)\\[ ([^]]+) \\](?![\\]])",
      "replace": "[[ \\1 ]]",
      "greedy": true
    },
 ```

**Comment by facelessuser** [comment] 2023-08-30 23:26
Alight, sounds like this issue has been confirmed as resolved. Closing.

**Closed by facelessuser** 2023-08-30 23:26 UTC
Labels: S: triage
